name: credentials_helper
description: Provides a helper class to simplify loading credentials from JSON
version: 1.0.1
author: "Herohtar <belac1186@gmail.com>"
homepage: https://github.com/herohtar/credentials_helper

dependencies:
  json_annotation: ^0.2.9

dev_dependencies:
  test: ^1.2.0
  build_runner: ^0.9.1
  json_serializable: ^0.5.8

environment:
  sdk: ">=2.0.0-dev.58.0 <2.0.0"
