name: credentials_helper
description: Provides a helper class to simplify loading credentials from JSON
version: 1.0.4
author: "Herohtar <belac1186@gmail.com>"
homepage: https://github.com/herohtar/credentials_helper

dependencies:
  built_value: ^6.7.0
  built_collection: ^4.2.2

dev_dependencies:
  test: ^1.6.5
  build_runner: ^1.6.5
  built_value_generator: ^6.7.0

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"
